---
# tasks file for configure_sshd

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define configure_sshd_name.
  set_fact:
    configure_sshd_name: "{{ __configure_sshd_name }}"
    when: configure_sshd_name is not defined

- name: Define configure_sshd_syslogfacility.
  set_fact:
    configure_sshd_syslogfacility: "{{ __configure_sshd_syslogfacility }}"
    when: configure_sshd_syslogfacility is not defined

- name: Define configure_sshd_sftpserver.
  set_fact:
    configure_sshd_sftpserver: "{{ __configure_sshd_sftpserver }}"
    when: configure_sshd_sftpserver is not defined

- name: Get openssh version.
  shell: |
    set -o pipefail
    ssh -V 2>&1 | sed -r "s/.*_([0-9]*\.[0-9]).*/\1/g"
  args:
    executable: /bin/bash
  register: sshd_version
  check_mode: false
  changed_when: false

- name: Set KEX algorithm for openssh 7.3 and above.
  set_fact:
    configure_sshd_kexalgorithms: '{{ configure_sshd_kexalgorithms_73 }}'
  when: sshd_version.stdout >= "7.3"

- name: Update the sshd configuration.
  template:
    src: "etc/ssh/{{ item }}.j2"
    dest: "/etc/ssh/{{ item }}"
    owner: root
    group: root
    mode: 0600
    validate: 'sshd -t -f %s'
    backup: true
  with_items:
    - sshd_config
  notify: Restart ssh service

- name: Ensure the directory {{ configure_sshd_authorizedkeysfile_dir }} is present.
  file:
    path: "{{ configure_sshd_authorizedkeysfile_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: configure_sshd_authorizedkeysfile_create_dir | bool

- name: Ensure the group {{ configure_sshd_allowgroups }} is present.
  group:
    name: "{{ configure_sshd_allowgroups }}"
    state: present
  when: configure_sshd_allowgroups_create_group | bool

- name: Set {{ configure_sshd_allowgroups_user }} user to be a member of {{ configure_sshd_allowgroups }} group.
  user:
    name: '{{ configure_sshd_allowgroups_user }}'
    groups: '{{ configure_sshd_allowgroups }}'
    append: true
  when: configure_sshd_allowgroups_create_group | bool
